server:
  port: 8086
spring:
  application:
    name: GATEWAY-SERVICE
    gateway:
      discovery:
        locator:
          enabled: true #Enable the function of dynamically creating routes from the regis
      routes:
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**      
#SECURITY CONFIGS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/auth/realms/protocol/openid-connect/jwks
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka