spring:
  application:
    name: customerservice
  datasource:
   url: jdbc:mysql://localhost:3306/bookstore
   username: root
   password: root
  jpa:
   hibernate:
    ddl-auto: update
   properties:
    hibernate:
     #dialect: org.hibernate.dialect.Oracle12cDialect
springdoc:
  api-docs:
   path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html
server:
  port: 8082
# Discovery Service address
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka