server:
  port: 8080
  tomcat: 
    max-threads: 3000
spring:
  application:
    name: AUTHORIZATION_SERVICE
# Discovery Service address
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jasypt:
  encryptor:
    password: Th3Lon3stP@ssword23
app:
  token:
    issuer: http://localhost:8080

