server:
  port: 8099
  tomcat: 
    max-threads: 3000
spring:
  application:
    name: AUTHORIZATION_SERVICE
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        client:
          articles-client:
            registration:
              client-id: articles-client
              client-secret: "{noop}secret"
              client-name: Articles Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/login/oauth2/code/articles-client-oidc
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - articles.read
jasypt:
  encryptor:
    password: Th3Lon3stP@ssword23

  