spring:
  application:
    name: BOOK-SERVICE
  datasource:
   url: jdbc:mysql://localhost:3306/bookstore
   username: root
   password: root
  jpa:
   hibernate:
    ddl-auto: update
   properties:
    hibernate:
     #dialect: org.hibernate.dialect.Oracle12cDialect
#SECURITY CONFIGS
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8080/auth/realms/protocol/openid-connect/jwks     
server:
  port: 8081
springdoc:
  api-docs:
   path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html
# Discovery Service address
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
